replicaCount: 2

# 공통 service 템플릿 설정용
serviceDefaults:
  type: NodePort

# gatewayService config
gatewayService:
  image:
    repository: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-gateway-service
    tag: "1.0.0"
  port: 8080

  env:
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: eouil-secret
          key: jwt-secret

# authService config
authService:
  image:
    repository: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-auth-service
    tag: "1.0.0"
  port: 8081
  env:
    - name: SPRING_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: spring-mysql-auth-secret
          key: SPRING_DATASOURCE_URL
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: spring-mysql-auth-secret
          key: SPRING_DATASOURCE_USERNAME
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: spring-mysql-auth-secret
          key: SPRING_DATASOURCE_PASSWORD
    - name: REDIS_HOST
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: REDIS_HOST
    - name: REDIS_PORT
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: REDIS_PORT
    - name: KAFKA_BOOTSTRAP_SERVERS
      valueFrom:
        secretKeyRef:
          name: spring-kafka-secret
          key: KAFKA_BOOTSTRAP_SERVERS
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: eouil-jwt-secret
          key: JWT_SECRET

# acService config
acService:
  image:
    repository: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-ac-service
    tag: "1.0.0"
  port: 8082
  env:
    - name: SPRING_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: spring-mysql-ac-secret
          key: SPRING_DATASOURCE_URL
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: spring-mysql-ac-secret
          key: SPRING_DATASOURCE_USERNAME
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: spring-mysql-ac-secret
          key: SPRING_DATASOURCE_PASSWORD
    - name: REDIS_HOST
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: REDIS_HOST
    - name: REDIS_PORT
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: REDIS_PORT
    - name: KAFKA_BOOTSTRAP_SERVERS
      valueFrom:
        secretKeyRef:
          name: spring-kafka-secret
          key: KAFKA_BOOTSTRAP_SERVERS
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: eouil-jwt-secret
          key: JWT_SECRET

mysql-ac:
  primary:
    resources:
      requests:
        cpu: "128m"
        memory: "512Mi"
      limits:
        cpu: "256m"
        memory: "1Gi"
    persistence:
      enabled: true
      size: 256Mi
      storageClass: gp2
    auth:
      existingSecret: mysql-ac-secret
      rootPassword: ""
      database: acdb
      username: acuser
      password: ""
mysql-auth:
  primary:
    resources:
      requests:
        cpu: "128m"
        memory: "512Mi"
      limits:
        cpu: "256m"
        memory: "1Gi"
    persistence:
      enabled: true
      size: 256Mi
      storageClass: gp2
    auth:
      existingSecret: mysql-auth-secret
      rootPassword: ""
      database: authdb
      username: authuser
      password: ""
redis:
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 256Mi
      storageClass: gp2
    auth:
      enabled: false
  resources:
    requests:
      cpu: "128m"
      memory: "256Mi"
    limits:
      cpu: "256m"
      memory: "512Mi"
kafka:
  replicaCount: 1
  image:
    tag: 3.5.1
  auth:
    clientProtocol: plaintext
    interBrokerProtocol: plaintext
  persistence:
    enabled: true
    size: 256Mi
    storageClass: gp2
  resources:
    requests:
      cpu: "128m"
      memory: "256Mi"
    limits:
      cpu: "256m"
      memory: "512Mi"
  zookeeper:
    replicaCount: 1
    persistence:
      enabled: true
      size: 1Gi
      storageClass: gp2
    resources:
      requests:
        cpu: "128m"
        memory: "256Mi"
      limits:
        cpu: "256m"
        memory: "512Mi"