# helm_values.yaml

# ----------------------------
# 공통 설정
# ----------------------------
certificateArn: "arn:aws:acm:ap-northeast-2:640168458081:certificate/xxxxxx"
domainName: "api.eouil.com"

replicaCount: 2
serviceDefaults:
  type: NodePort

# ----------------------------
# Gateway Service
# ----------------------------
gatewayService:
  image:
    repository: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-gateway-service
    tag: "1.0.38"
  port: 80
  targetPort: 8080
  nodePort: 30080
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: eouil-jwt-secret
          key: JWT_SECRET

# ----------------------------
# Auth Service
# ----------------------------
authService:
  image:
    repository: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-auth-service
    tag: "1.0.43"
  port: 8081
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: SERVER_PORT
      value: "8081"
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://eouil-services-mysql-auth.default.svc.cluster.local:3306/authdb
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: spring-mysql-auth-secret
          key: SPRING_DATASOURCE_USERNAME
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: spring-mysql-auth-secret
          key: SPRING_DATASOURCE_PASSWORD
    - name: REDIS_HOST
      value: redis
    - name: REDIS_PORT
      value: "6379"
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: eouil-jwt-secret
          key: JWT_SECRET
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_ACCESS_KEY_ID

    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_SECRET_ACCESS_KEY

# ----------------------------
# AC Service
# ----------------------------
acService:
  image:
    repository: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-ac-service
    tag: "1.0.34"
  port: 8082
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: SERVER_PORT
      value: "8082"
    - name: SPRING_DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: spring-mysql-ac-secret
          key: SPRING_DATASOURCE_URL
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: spring-mysql-ac-secret
          key: SPRING_DATASOURCE_USERNAME
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: spring-mysql-ac-secret
          key: SPRING_DATASOURCE_PASSWORD
    - name: REDIS_HOST
      value: redis
    - name: REDIS_PORT
      value: "6379"
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: eouil-jwt-secret
          key: JWT_SECRET
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_ACCESS_KEY_ID

    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: AWS_SECRET_ACCESS_KEY


