apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-pod-deploy
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: "{{ .Values.authService.image.repository }}:{{ .Values.authService.image.tag }}"
          ports:
            - containerPort: {{ .Values.authService.port }}
          env:
{{ toYaml .Values.authService.env | nindent 12 }}
