apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
  namespace: default
  labels:
    app: gateway-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8080  # 사용 안 하면 제거해도 됨
  selector:
    app: gateway-service
