apiVersion: v1
kind: Service
metadata:
  name: ac-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.acService.port }}
      targetPort: {{ .Values.acService.port }}
  selector:
    app: ac-service