apiVersion: v1
kind: Service
metadata:
  name: ac-service
  namespace: default
  labels:
    app: ac-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8082
  selector:
    app: ac-service
