apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.gatewayService.port }}
      nodePort: {{ .Values.gatewayService.nodePort }}
  selector:
    app: gateway-service
