apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
  namespace: default
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.gatewayService.port }}
    - name: https
      port: 443
      targetPort: 8443  # 사용 안 하면 제거해도 됨
  selector:
    app: gateway-service
