apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.port }}
  selector:
    app: auth-service