apiVersion: v1
kind: Service
metadata:
  name: ac-service-svc
  namespace: default
  labels:
    app: ac-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.acService.port }}
    - name: https
      port: 443
      targetPort: 8443  # 사용하지 않는다면 이 줄 제거해도 OK
  selector:
    app: ac-service
