#Gateway-service.yaml

gatewayService:
  applicationConfig:
    spring:
      config:
        activate:
          on-profile: prod
      cloud:
        gateway:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "https://app.eouil.com"
                  - "https://eouil.com"
                  - "http://eouil.com"
                  - "https://api.eouil.com"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "Origin"
                  - "Content-Type"
                  - "Accept"
                  - "Authorization"
                  - "X-Requested-With"
                  - "Access-Control-Request-Method"
                  - "Access-Control-Request-Headers"
                allowCredentials: true
                maxAge: 3600
          routes:
            - id: user-public
              uri: http://auth-service.default.svc.cluster.local:80
              predicates:
                - Path=/api/users/join,/api/users/login,/api/users/logout
                - Host=api.eouil.com
                - Method=POST

            - id: user-service
              uri: http://auth-service.default.svc.cluster.local:80
              predicates:
                - Path=/api/users/**
                - Host=api.eouil.com
              filters:
                - CookieToHeader
                - AuthorizationHeader
                - RewritePath=/api/users/(?<segment>.*), /${segment}

            - id: accounts
              uri: http://accounts.default.svc.cluster.local:80
              predicates:
                - Path=/api/accounts/**
                - Host=api.eouil.com
              filters:
                - CookieToHeader
                - AuthorizationHeader

            - id: transactions
              uri: http://transactions.default.svc.cluster.local:80
              predicates:
                - Path=/api/transactions/**
                - Host=api.eouil.com
              filters:
                - CookieToHeader
                - AuthorizationHeader

  management:
    endpoints:
      web:
        exposure:
          include: health
        base-path: /actuator
        cors:
          allowed-origins:
            - "http://localhost:5173"
            - "https://app.eouil.com"
            - "https://eouil.com"
            - "https://api.eouil.com"
          allowed-methods:
            - GET
            - OPTIONS
          allowed-headers:
            - "*"
          allow-credentials: true
          max-age: 3600
    endpoint:
      health:
        show-details: always
