logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    com.eouil.msa.gateway: DEBUG

spring:
  cloud:
    gateway:
      # 1) 전역 CORS 설정
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - "Set-Cookie"
              - "Authorization"
            maxAge: 3600  # preflight 캐시 시간 설정

      # 2) 라우팅
      routes:
        # (A) user-public: 로그인/회원가입 → CookieToHeader만 필요
        - id: user-public
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/join, /api/users/login, /api/users/logout
            - Method=POST
          filters:
            - PreserveSetCookie

        # (B) user-service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - CookieToHeader
            - AuthorizationHeader
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}

        # (C) accounts
        - id: accounts
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
          filters:
            - CookieToHeader
            - AuthorizationHeader

        # (D) transactions
        - id: transactions
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
          filters:
            - CookieToHeader
            - AuthorizationHeader
