spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: user-public
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/join, /api/users/login, /api/users/logout
            - Host=api.eouil.com
            - Method=POST
          filters:
            - PreserveSetCookie

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
            - Host=api.eouil.com
          filters:
            - CookieToHeader
            - AuthorizationHeader
            - RewritePath=/api/users/(?<segment>.*), /${segment}

        - id: accounts
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
            - Host=api.eouil.com
          filters:
            - CookieToHeader
            - AuthorizationHeader

        - id: transactions
          uri: http://localhost:8082
          predicates:
            - Path=/api/transactions/**
            - Host=api.eouil.com
          filters:
            - CookieToHeader
            - AuthorizationHeader
