spring:
  profiles:
    active: prod

  server:
    port: 8080

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "https://app.eouil.com"
              - "https://eouil.com"
              - "https://api.eouil.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - "Set-Cookie"
              - "Authorization"
            maxAge: 3600
