apiVersion: v1
kind: Secret
metadata:
  name: eouil-jwt-secret
  namespace: default
type: Opaque
data:
  jwt-secret: sFlETs6NviTGD/IAQmyUTsrOd73JMMik9SA8fKFaTsMCBAlCrRrgSTI49i22NPHjQZ/NN8Q9V66oBQibJQjC3A==
