apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 640168458081.dkr.ecr.ap-northeast-2.amazonaws.com/eouil-gateway-service:1.0.1
          ports:
            - containerPort: 8080
