spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL} # AWS Secrets Manager에서 읽어올 변수
    username: ${SPRING_DATASOURCE_USERNAME} # AWS Secrets Manager에서 읽어올 변수
    password: ${SPRING_DATASOURCE_PASSWORD} # AWS Secrets Manager에서 읽어올 변수
    driver-class-name: com.mysql.cj.jdbc.Driver # 운영 환경의 MySQL 드라이버

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST} # 운영 환경의 Redis 호스트 (환경 변수 또는 Secrets Manager)
      port: ${REDIS_PORT} # 운영 환경의 Redis 포트 (환경 변수 또는 Secrets Manager)

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS} # 운영 환경의 Kafka 브로커 주소 (환경 변수 또는 Secrets Manager)