spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL} # AWS Secrets Manager에서 읽어올 변수
    username: ${SPRING_DATASOURCE_USERNAME} # AWS Secrets Manager에서 읽어올 변수
    password: ${SPRING_DATASOURCE_PASSWORD} # AWS Secrets Manager에서 읽어올 변수
    driver-class-name: com.mysql.cj.jdbc.Driver # 운영 환경의 MySQL 드라이버

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: default

  kafka:
    bootstrap-servers: "eouil-services-kafka-controller-0.eouil-services-kafka-controller-headless.default.svc.cluster.local:9092"
    producer:
      retries: 3
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        max.request.size: 2097152
        request.timeout.ms: 30000
        retry.backoff.ms: 1000
        compression.type: snappy