apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ac
  template:
    metadata:
      labels:
        app: mysql-ac
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysqlRootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysqlDatabase }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysqlUser }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysqlPassword }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mysql-storage

