spring:
  config:
    activate:
      on-profile: dev

  logging:
    level:
      com.eouil.msa.money.account.controllers: DEBUG

  datasource:
    url: jdbc:h2:mem:moneydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092 # 개발 환경의 Kafka 브로커 주소

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.eouil.msa.shared.kafka"
        spring.json.value.default.type: com.eouil.msa.shared.kafka.UserCreatedEvent
