spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL} # AWS Secrets Manager에서 읽어올 변수
    username: ${SPRING_DATASOURCE_USERNAME} # AWS Secrets Manager에서 읽어올 변수
    password: ${SPRING_DATASOURCE_PASSWORD} # AWS Secrets Manager에서 읽어올 변수
    driver-class-name: com.mysql.cj.jdbc.Driver # 운영 환경의 MySQL 드라이버

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: "eouil-services-kafka-controller-0.eouil-services-kafka-controller-headless.default.svc.cluster.local:9092"
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.eouil.msa.shared.kafka"
        spring.json.value.default.type: "com.eouil.msa.shared.kafka.UserCreatedEvent"