spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL} # AWS Secrets Manager에서 읽어올 변수
    username: ${SPRING_DATASOURCE_USERNAME} # AWS Secrets Manager에서 읽어올 변수
    password: ${SPRING_DATASOURCE_PASSWORD} # AWS Secrets Manager에서 읽어올 변수
    driver-class-name: com.mysql.cj.jdbc.Driver # 운영 환경의 MySQL 드라이버

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.eouil.msa.shared.kafka"
        spring.json.value.default.type: "com.eouil.msa.shared.kafka.UserCreatedEvent"

logging:
  level:
    org.springframework.kafka.listener: DEBUG
    org.apache.kafka.clients.consumer: DEBUG
    com.eouil.msa.money.account.kafka: DEBUG

aws:
  sqs:
    userCreatedQueueUrl: https://sqs.ap-northeast-2.amazonaws.com/640168458081/Eouil-AC.fifo
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}