logging:
  level:
    root: INFO
    com.eouil.msa.money.account.controllers: DEBUG

server:
  port: 8082

spring:
  config:
    import: optional:aws-secretsmanager:/eouil

  datasource:
    url: jdbc:h2:mem:moneydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost # Redis는 localhost로 접근 가능
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092 #
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.eouil.msa.shared.kafka"
        spring.json.value.default.type: com.eouil.msa.shared.kafka.UserCreatedEvent

jwt:
  secret: ${JWT_SECRET}