image:
  tag: 8.0.36
primary:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp3
  auth:
    rootPassword: Goorm!
    database: acdb
    username: acuser
    password: acpass
  service:
    port: 3306
