image:
  tag: 8.0.36
primary:
  resources:
    requests:
      cpu: "128m"
      memory: "512Mi"
    limits:
      cpu: "256m"
      memory: "1Gi"
  persistence:
    enabled: true
    size: 256Mi
    storageClass: gp2
  auth:
    rootPassword: Goorm!
    database: acdb
    username: acuser
    password: acpass
  service:
    port: 3306