# kafka-values.yaml
replicaCount: 1
image:
  tag: 3.5.1
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
persistence:
  enabled: true
  size: 128Mi
  storageClass: gp2
resources:
  requests:
    cpu: "128m"
    memory: "256Mi"
  limits:
    cpu: "256m"
    memory: "512Mi"
zookeeper:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp2
