architecture: standalone
master:
  persistence:
    enabled: true
    size: 128Mi
    storageClass: gp2
  resources:
    requests:
      cpu: "128m"
      memory: "256Mi"
    limits:
      cpu: "256m"
      memory: "512Mi"
  auth:
    enabled: false
